In [1]:
import numpy as np

In [ ]:
a = np.int8(25)
print(a)
# 25

print(type(a))
# <class 'numpy.int8'>

In [ ]:
# Можно применить к самому
# названию типа данных
np.iinfo(np.int8)
# iinfo(min=-128, max=127, dtype=int8)

# Можно применить к существующему
# конкретному объекту
np.iinfo(a)
# iinfo(min=-128, max=127, dtype=int8)

In [ ]:
a = np.int32(1000)
print(a)
# 1000
print(type(a))
# <class 'numpy.int32'>
a = 2056
print(a)
# 2056
print(type(a))
# <class 'int'>

In [ ]:
a = np.int32(1000)
b = a + 25
print(b)
# 1025
print(type(b))
# <class 'numpy.int64'>

In [7]:
a = [1,2,3,4]
map(np.int8, a)
type(a[0])
np.int8(a)

array([1, 2, 3, 4], dtype=int8)

In [8]:
a = np.int32(1000)
b = np.int8(25)
c = a + b
print(c)
# 1025
print(type(c))
# <class 'numpy.int32'>

1025
<class 'numpy.int32'>


In [10]:
a = np.int8(127)
print(a)
# 4

127


In [ ]:
a = np.int32(2147483610)
b = np.int32(2147483605)
print(a, b)
# 2147483610 2147483605
print(a + b)
# -81
# RuntimeWarning: overflow encountered in int_scalars
# Переполнено int'овое значение

a = np.int32(2147483610)
b = np.int32(2147483605)
print(a, b)
# 2147483610 2147483605
print(np.int64(a) + np.int64(b))
# 4294967215

In [ ]:
np.finfo(np.float16)
# finfo(resolution=0.001, min=-6.55040e+04, max=6.55040e+04, dtype=float16)
np.finfo(np.float32)
# finfo(resolution=1e-06, min=-3.4028235e+38, max=3.4028235e+38, dtype=float32)
np.finfo(np.float64)
# finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)
np.finfo(np.float128)
# finfo(resolution=1e-18, min=-1.189731495357231765e+4932, max=1.189731495357231765e+4932, dtype=float128)

In [ ]:
print(np.float16(4.12))
# 4.12
print(np.float16(4.13))
# 4.13
print(np.float16(4.123))
# 4.12
print(np.float16(4.124))
# 4.125
print(np.float16(4.125))
# 4.125

In [ ]:
a = True
print(type(a))
# <class 'bool'>
a = np.bool(a)
print(type(a))
# <class 'bool'>
a = np.bool_(a)
print(type(a))
# <class 'numpy.bool_'>
 
# Значения равны
print(np.bool(True) == np.bool_(True))
# True
# А типы — нет:
print(type(np.bool(True)) == type(np.bool_(True)))
# False

In [ ]:
a = "Hello world!"
print(type(a))
# <class 'str'>
a = np.str(a)
print(type(a))
# <class 'str'>
a = np.str_(a)
print(type(a))
# <class 'numpy.str_'>
print(a)

## array

In [13]:
arr = np.array([1,5,2,9,10])
arr
#array([ 1,  5,  2,  9, 10])

array([ 1,  5,  2,  9, 10])

In [ ]:
print(type(arr))
# <class 'numpy.ndarray'>

arr.dtype
# dtype('int32')

In [14]:
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ])
nd_arr
# array([[12, 45, 78],
#        [34, 56, 13],
#        [12, 98, 76]])

array([[12, 45, 78],
       [34, 56, 13],
       [12, 98, 76]])

.ndim .size .shape .itemsize

In [ ]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)

arr.ndim
# 1
nd_arr.ndim
# 2
arr.size
# 5
nd_arr.size
# 9
arr.shape
# (5,)
nd_arr.shape
# (3, 3)
arr.itemsize
# 1
nd_arr.itemsize
# 2

zeros

In [17]:
zeros_1d = np.zeros(5)
zeros_1d
# array([0., 0., 0., 0., 0.])

zeros_2d = np.zeros((5,4), dtype=np.float32)
print(zeros_2d.shape)
# (5, 4)

zeros_2d

(5, 4)


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

np.arrange

In [ ]:
np.arange(5)
# array([0, 1, 2, 3, 4])

np.arange(2.5, 5)
# array([2.5, 3.5, 4.5])

np.arange(2.5, 5, 0.5)
# array([2.5, 3. , 3.5, 4. , 4.5])

np.arange(2.5, 5, 0.5, dtype=np.float16)
# array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

linspace

In [ ]:
arr = np.linspace(1, 2, 10)
arr
# array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
#        1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

arr = np.linspace(1, 2, 10, endpoint=False)
arr
# array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

arr, step = np.linspace(1, 2, 10, endpoint=True, retstep=True)
print(step)
# 0.1111111111111111

arr, step = np.linspace(1, 2, 10, endpoint=False, retstep=True)
print(step)
# 0.1

.shape .reshape

In [18]:
arr = np.arange(8)
arr
# array([0, 1, 2, 3, 4, 5, 6, 7])

arr.shape = (2, 4)
arr
# array([[0, 1, 2, 3],
#        [4, 5, 6, 7]])

arr = np.arange(8)
arr_new = arr.reshape((2, 4))
arr_new
# array([[0, 1, 2, 3],
#       [4, 5, 6, 7]])

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
arr = np.arange(8)
arr_new = arr.reshape((2, 4), order='F')
arr_new
# array([[0, 2, 4, 6],
#       [1, 3, 5, 7]])


transpose()

In [ ]:

arr = np.arange(8)
arr.shape = (2, 4)
arr
# array([[0, 1, 2, 3],
#        [4, 5, 6, 7]])

arr_trans = arr.transpose()
arr_trans
# array([[0, 4],
#        [1, 5],
#        [2, 6],
#        [3, 7]])

arr[]

In [ ]:
arr = np.linspace(1, 2, 6)
arr
# array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

print(arr[2])
# 1.4

print(arr[2:4])
# [1.4 1.6]

print(arr[::-1])
# [2.  1.8 1.6 1.4 1.2 1. ]

nd_array =  np.linspace(0, 6, 12, endpoint=False).reshape(3,4)
nd_array
# array([[0. , 0.5, 1. , 1.5],
#        [2. , 2.5, 3. , 3.5],
#        [4. , 4.5, 5. , 5.5]])


nd_array[1][2]
# 3.0
nd_array[1,2]
# 3.0

nd_array[:2, 2]
# array([1., 3.])

nd_array[1:, 2:4]
# array([[3. , 3.5],
#       [5. , 5.5]])

nd_array[:, 2:4]
# array([[1. , 1.5],
#       [3. , 3.5],
#       [5. , 5.5]])

nd_array[:2]
# array([[0. , 0.5, 1. , 1.5],
#       [2. , 2.5, 3. , 3.5]])

.sort()

In [ ]:
arr = np.array([23,12,45,12,23,4,15,3])

print(arr)
# [23 12 45 12 23  4 15  3]
arr_new = np.sort(arr)

print(arr_new)
# [ 3  4 12 12 15 23 23 45]

arr = np.array([23,12,45,12,23,4,15,3])
print(arr.sort())
# None
print(arr)
# [ 3  4 12 12 15 23 23 45]

arr = np.array([23,12,45,12,23,4,15,3])
arr.shape = (2,4)
display(arr)

#array([[23, 12, 45, 12],
#       [23,  4, 15,  3]])

arr_new = np.sort(arr)
display(arr_new)

#array([[12, 12, 23, 45],
#       [ 3,  4, 15, 23]])

.isnan .sqrt

In [62]:
data = np.array([4, 9, -4, 3])

roots = np.sqrt(data)
print(roots)
# RuntimeWarning: invalid value encountered in sqrt
# array([2.        , 3.        ,        nan, 1.73205081])

print(np.isnan(roots))
# array([False, False,  True, False])

roots[np.isnan(roots)] = 0
roots
# array([2.        , 3.        , 0.        , 1.73205081])

[2.         3.                nan 1.73205081]
[False False  True False]


C:\Users\Boris\AppData\Local\Temp\ipykernel_21556\726446747.py:3: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(data)


array([2.        , 3.        , 0.        , 1.73205081])

np.linalg vectors

In [ ]:
import numpy as np
vec1 = np.array ([2, 4, 7 , 2.5])
vec2 = np.array ([12 ,6 ,3.5, 13])

vec1 + vec2

#array([14. , 10. , 10.5, 15.5])

vec = np.arange(5)
vec ** 2
#array([ 0,  1,  4,  9, 16])

vec1>vec2
#array([False, False,  True, False])


In [ ]:
vec = np.array([3,4])
length = np.linalg.norm(vec)
print(length)
#5.0

np.dot

In [64]:
vec1 = np.arange(1,6)
vec2 = np.linspace(10, 20, 5)
scalar_product = np.sum(vec1 * vec2)
print(scalar_product)

#250.0

scalar_product = np.dot(vec1,vec2)
scalar_product

#250.0

250.0


250.0

.min() .max() .mean()

In [ ]:
vec = np.array([2, 7, 18, 28, 18 , 1 ,8, 4])
print(vec.min())
#1
print(vec.max())
#28
print(vec.mean())
#10.75
print(np.min(vec))
#1
print(np.max(vec))
#28
print(np.mean(vec))

## random

In [ ]:
np.random.rand()
# 0.06600758835806675

np.random.rand() * 100
# 69.76076924077643

np.random.rand(5)
# array([0.83745099, 0.58426808, 0.89206204, 0.41149807, 0.42445145])]

np.random.rand(2, 3)
# array([[0.94931212, 0.06680018, 0.26707599],
#      [0.67908873, 0.18001743, 0.97732239]])

.shape()

In [ ]:
shape = (3, 4)
np.random.rand(shape)
# TypeError: 'tuple' object cannot be interpreted as an integer
# Ошибка типов: кортеж не может быть интерпретирован как целое число.

shape = (3, 4)
np.random.rand(*shape)
# array([[0.66169176, 0.19455777, 0.06451088, 0.31919608],
#        [0.73536951, 0.67104408, 0.4762727 , 0.88153576],
#        [0.70672971, 0.96677145, 0.09273995, 0.86356465]])

shape = (2, 3)
np.random.sample(shape)
# array([[0.39756103, 0.01995168, 0.2768951 ],
#       [0.82195372, 0.26435273, 0.00957881]])

.uniform()

In [ ]:
np.random.uniform()
# 0.951557685543591

np.random.uniform(-30, 50)
# 38.47365525953661

np.random.uniform(0.5, 0.75, size=5)
# array([0.58078945, 0.58860342, 0.73790553, 0.63448265, 0.70920297])

np.random.uniform(-1000, 500, size=(2, 3))
# array([[ 129.22164163,   77.69090611, -132.9656972 ],
#        [  18.65802226, -317.14793906,   85.3613547 ]])

.randint()

In [ ]:
np.random.randint(4, size=(2,3))
# array([[3, 0, 1],
#       [2, 1, 3]])

np.random.randint(6, 12, size=(3,3))
# array([[ 9,  6, 10],
#        [10, 11, 10],
#        [ 7, 10, 11]])

.shuffle()

In [ ]:
arr = np.arange(6)
print(arr)
# [0 1 2 3 4 5]
print(np.random.shuffle(arr))
# None
arr
# array([0, 5, 1, 3, 2, 4])

In [ ]:
playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]
shuffled = np.random.permutation(playlist)
print(shuffled)
# ['The Beatles' 'Pink Floyd' 'Deep Purple' 'ACDC']
print(playlist)
# ['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']

.choice()

In [65]:
#a — одномерный массив или число для генерации arange(a);
#size — желаемая форма массива (число для получения одномерного массива, кортеж — для многомерного; если параметр не задан, возвращается один объект);
#replace — параметр, задающий, могут ли элементы повторяться (по умолчанию могут).

workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
choice = np.random.choice(workers, size=10)
print(choice)

workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
choice = np.random.choice(workers, size=10, replace=False)
print(choice)
# ValueError: Cannot take a larger sample than population when 'replace=False'
# Ошибка значения: нельзя получить выборку больше, чем популяция (популяция — весь доступный набор объектов, из которого получаем выборку), если replace=False (то есть выборка без повторений).

['Ivan' 'Nikita' 'John' 'Maria' 'John' 'Ivan' 'Nikita' 'John' 'John'
 'Ivan']


ValueError: Cannot take a larger sample than population when 'replace=False'

In [67]:
np.random.seed(23)
np.random.randint(10, size=(3,4))
# array([[3, 6, 8, 9],
#        [6, 8, 7, 9],
#        [3, 6, 1, 2]])

array([[3, 6, 8, 9],
       [6, 8, 7, 9],
       [3, 6, 1, 2]])

In [78]:
np.random.seed(100)
print(np.random.randint(10, size=3))
# [8 8 3]
print(np.random.randint(10, size=3))
# [7 7 0]
print(np.random.randint(10, size=3))
# [4 2 5]

[2 2 2]
[8 8 3]
[7 7 0]
[4 2 5]
